name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-prediction-orchestrator:
    name: Build and push prediction-orchestrator
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: prediction-orchestrator
      image-name: prediction-orchestrator
    secrets: inherit
